version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  the-coffee-bar:
    image: sumo/the-coffee-bar-app:python-apps
    container_name: the-coffee-bar
    hostname: the-coffee-bar
    ports:
      - 8082:8082
    expose:
      - 8082
    command: ["the-coffee-bar",
              "--host=the-coffee-bar", "--port=8082", "--coffeemachine-host=the-coffee-machine",
              "--coffeemachine-port=8083", "--cashdesk-host=the-cashdesk", "--cashdesk-port=8084"]
  the-coffee-bar-frontend:
    image: sumo/the-coffee-bar-app:js-apps
    container_name: the-coffee-bar-frontend
    hostname: the-coffee-bar-frontend
    ports:
      - 3000:3000
    expose:
      - 3000
    command: |
      /bin/bash -c "python3 ./cpu_killer/cpu_killer.py & \
       npm start"
    environment:
      - INTERVAL=5
      - DURATION=1
      - THREADS_NO=500
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_COFFEE_BAR_URL=http://localhost:8082/order
  the-coffee-machine:
    image: sumo/the-coffee-bar-app:python-apps
    container_name: the-coffee-machine
    hostname: the-coffee-machine
    ports:
      - 8083:8083
    command: ["python3", "src/bin/the_coffee_machine.py",
              "--host=the-coffee-machine", "--port=8083", "--machine-svc-host=machine-svc",
              "--machine-svc-port=9090"]
  the-cashdesk:
    image: sumo/the-coffee-bar-app:python-apps
    container_name: the-cashdesk
    hostname: the-cashdesk
    ports:
      - 8084:8084
    command: ["python3", "src/bin/the_cashdesk.py",
              "--host=the-cashdesk", "--port=8084", "--calculator-host=calculator-svc", "--calculator-port=8090",
              "--connection-string=postgresql://account:account@postgres:5432/account"]
  the-coffee-lover:
    image: sumo/the-coffee-bar-app:python-apps
    container_name: the-coffee-lover
    hostname: the-coffee-lover
    command: ["python3", "src/bin/the_coffee_lover.py",
              "--host=the-coffee-bar", "--port=8082", "--ratio=1"]
  machine-svc:
    image: sumo/the-coffee-bar-app:ruby-apps
    container_name: machine-svc
    hostname: machine-svc
    ports:
      - 9090:9090
    command: ["ruby", "/app/lib/machine.rb"]
  coffee-svc:
    image: sumo/the-coffee-bar-app:ruby-apps
    container_name: coffee-svc
    hostname: coffee-svc
    ports:
      - 9091:9091
    command: ["ruby", "/app/lib/coffee.rb"]
  water-svc:
    image: sumo/the-coffee-bar-app:ruby-apps
    container_name: water-svc
    hostname: water-svc
    ports:
      - 9092:9092
    command: ["ruby", "/app/lib/water.rb"]
  calculator-svc:
    image: sumo/the-coffee-bar-app:calculator-dotnet
    container_name: calculator-svc
    hostname: calculator-svc
    command: ["dotnet", "dotnet-core-calculator-svc.dll", "http://calculator-svc:8090"]
    ports:
      - 8090:8090
  
